profiles:
  local:
    - docker-compose.yml

  test:
    - docker-compose.yml
    - results

tasks:
  jenkinslint:
    command: compose-flow compose run -u root:docker --rm app /bin/bash -c 'pylama -r results/pylama.log || /bin/true'

  publish:
    command: compose-flow compose run -u root:docker --rm app /bin/bash ./scripts/publish.sh
