profiles:
  local:
    - docker-compose.yml
    - mount

  test:
    - docker-compose.yml
    - results

  prod:
    - docker-compose.yml
    - publish

rancher:
  project: Ops

remotes:
  test:
    backend: rancher
  prod:
    backend: rancher

tasks:
  jenkinslint:
    command: compose-flow compose run --rm app /bin/bash -c 'pylama -r results/pylama.log -f pylint || /bin/true'

  jenkinstest:
    command: compose-flow compose run --rm app /bin/bash -c 'python -m unittest src/tests/test_*.py --junitxml=results/report.xml'

  publish:
    command: compose-flow compose run --rm app /bin/bash ./scripts/publish.sh
